name: Hola Mundo

on: [push]

jobs:
  uno:
    steps:
      - name: Mensaje
      - name: Touch File
        run: |
          touch hola.txt
          ls -al
      - name: Set test
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al
      - name: Read File
        run: |
          cat hola.txt
          ls -al
  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1    
      - name: Directorio
        run: ls -al
